### ISSUE TITLE
把print的部分合併到item裡面

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/Pulipuli-Blog#14]
````css
@media print { 
 /* All your print styles go here */
 #header, #footer, #nav { display: none !important; } 
}
````
