### ISSUE TITLE
Labels太長的地方，加入text-overflow: ellipsis;

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/Pulipuli-Blog#70]
嗎？
https://www.astralweb.com.tw/css-ellipsis/
https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

**Comment by pulipulichen** [comment]
http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/
此例爲正解
https://codepen.io/natonischuk/pen/QbGWBa

````scss
body {
  margin: 0;
  padding: 50px;
  font: 400 14px/1.2em sans-serif; 
  background: white;
}

/* mixin for multiline */
@mixin multiLineEllipsis($lineHeight: 1.2em, $lineCount: 1, $bgColor: white){
  overflow: hidden;
  position: relative;
  line-height: $lineHeight;
  max-height: $lineHeight * $lineCount; 
  text-align: justify;
  margin-right: -1em;
  padding-right: 1em;
  &:before {
    content: '...';
    position: absolute;
    right: 0;
    bottom: 0;
  }
  &:after {
    content: '';
    position: absolute;
    right: 0;
    width: 1em;
    height: 1em;
    margin-top: 0.2em;
    background: $bgColor;
  }
}

.block-with-text {
  @include multiLineEllipsis($lineHeight: 1.2em, $lineCount: 3, $bgColor: white);  
}
````
